<?php

class Cylinder extends Circle
{
    public $height;

    public function __construct(string $name, $radius, $height)
    {
        parent::__construct($name, $radius);
        $this->height = $height;
    }

    public function calculateArea()
    {
        return parent::calculateArea() * 2 + parent::calculatePerimeter() * $this->height; // TODO: Change the autogenerated stub
    }

    public function calculateVolume()
    {
        return parent::calculateArea() * $this->height;
    }
}